ALTER TABLE Reservation
DROP CONSTRAINT FK_RES_PLA;
ALTER TABLE Reservation
DROP CONSTRAINT FK_RES_UTI;

ALTER TABLE Reservation
ADD CONSTRAINT FK_RES_UTI FOREIGN KEY (IdUser) 
REFERENCES Utilisateur (IdUser);

ALTER TABLE Reservation
ADD CONSTRAINT FK_RES_PLA FOREIGN KEY (NumPlace) 
REFERENCES Place (NumPlace);